### ISSUE TITLE
Build a NavBar for the application

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#3]
Need to build a functional navbar. Can worry about styling later. The Navbar should be visible across all pages.

Basic Functionality:
Act as the fundamental router for the app.

**Comment by dylrob34** [comment]
Nav bar could probably have a sub "User" component which is the little user widget thats usually on the top right of a page, this is where they can access "my profile" and logout, stuff like that. This component will also have the login dropdown built in. I can work on this part.
