### ISSUE TITLE
Metrics Table - Link Categories to Metrics Table

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#36]
CSS - Create the actual first draft of table

Create the link between the categories, cells, durations, times, and metrics table so that the behind-the-scenes logic exists for metrics to be calculated from.

**Comment by Cknutson100** [comment]
![image](https://user-images.githubusercontent.com/61856255/150707808-d10e0088-c4d2-4b7d-a87d-dfe32f8d5473.png)

This is what I think we should have as "barebones" metrics for the information that is populated in the table.

**Comment by dylrob34** [comment]
Pie chart is made, will have to talk about percentages and the table. Pie chart needs to be linked to categories. Should be simple fix, there are example inputs already.

**Comment by dylrob34** [comment]
Pie chart is linked to categories. Some pie chart bugs still. Table needs to be made. Pie chart improvements could be made such as title and moving percentages to be somewhere more meaningful, on the actual pie chart will be more complicated tho.

**Comment by Cknutson100** [comment]
The first rendering for the table is done.
1. Need to finish implementing
2. Need to link the categories with the metrics table once frontend styling is done.

**Comment by Cknutson100** [comment]
Very close just need to finish up moving this duration number over to the table and we should be good.
