### ISSUE TITLE
Time Blocking Table - Snapshot of previous weeks

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#37]
Minimum: Create functionality for bulk clearing and cleaning a weeks worth of time block content so that if the user wants to start over complete from scratch they can do so.

Functional: Create an archive of time block tables that the user can refer back to and see what they had inputted from past weeks. This would also serve as the means for generating longevity metrics and informing users how they are spending their time over long periods.

**Comment by dylrob34** [comment]
We probably want to stop the user from entering previous weeks.
