### ISSUE TITLE
Finish Signup Page

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#39]
Possibly try out new color palettes. Make sure that all the functionality works properly. 

1/19/22:
Last thing is to add back in the error indicators for email and password.

**Comment by Cknutson100** [comment]
CSS is completed need to validate that the functionality still works for everything. @Cknutson100 @dylrob34

**Comment by dylrob34** [comment]
@Cknutson100 can you add the validating email and confirming passwords match stuff back in ? I think kanishq removed it when he updated the page.

**Comment by Cknutson100** [comment]
@Cknutson100 do this tonight you fucking bonehead
