### ISSUE TITLE
Cell text input is shifted to the right now (Production build only?)

### ISSUE THREAD

**Issue by dylrob34** [dylrob34/toDo#49]
The right border of a cell disappears on double click.

1/19/22:
Size needs to scale with resolution ie its not bigger than the cell or smaller than the cell the size of the text box.

Also get wider in an empty cell

**Comment by Cknutson100** [comment]
Need updated Table style before we can address these tables. Or improve this table, whatever will be the best solution in the longe run.

**Comment by Cknutson100** [comment]
The text input for cells that are being edited is shifted to the right, it seems to only happen on production builds of the web app...really not sure what this is. 
Need to investigate.
