### ISSUE TITLE
Bug with Timeblock page - on Double click popup

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#54]
If I click on the time cell and I change that to a different time, and then I try and change the duration. It does not move the task to the new time (I think we are still working on this so that OK), but it also doesn't increase the duration and it just deletes the title from my timeblock table so I have to restart

**Comment by dylrob34** [comment]
We just have to have time changing refresh the page just like duration does, this will refresh the table and change the location of the block

**Comment by dylrob34** [comment]
Can prob call this finished ? Test again plz
