### ISSUE TITLE
Timeblocking table bug - Drag duration vs setting duration

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#55]
Setting the duration of the task works pretty flawlessly and it does not extend the cells in the table. However, I was able to get the drag functionality to work "sorta" and the first thing I noticed was that the table started extending past the bottom again.

**Comment by Cknutson100** [comment]
its something to do with re-rendering the frontend I think. I tested it out where I drug some cells to increase their size and it added extra cells to the bottom of the page and then when I manually set the time of a different cell to be a longer duration. it re-renders the frontend and fixed the drug cells to be the proper size. so we just have to figure out how to render on drag let go.

**Comment by dylrob34** [comment]
We still need to be able to drag and decrease duration. There is also a delay between the duration / time changing and the table updating it. I can probably fix that but its tedious so I don't want to rn

**Comment by Cknutson100** [comment]
Why don't we wait on this task until Kanishq gets done with the new table @dylrob34  @Neesh774

**Comment by dylrob34** [comment]
I want to do this a different way now, right now were highlighting cells to sort of show the duration increase, instead I want to actually update the duration but not save in the backend till the user releases the mouse. Increasing time above will work the same but will change the start time as well as increase the duration. With this method we should be looking at the time cells locations to tell how many cells have been moved, this will allow us to decrease the duration of a cell as well. Location thing is iffy though, hopefully using time cells, which don't move, will fix this.

**Comment by Cknutson100** [comment]
I think this is done based on functionality...

**Comment by Cknutson100** [comment]
Need to focus on drag up. There is still some bugginess there with either pulling from the top of cell OR pushing the bottom of the cell up.
