### ISSUE TITLE
Due Dates on Tasks #ToDoPage

### ISSUE THREAD

**Issue by Cknutson100** [dylrob34/toDo#66]
Backend: Need to figure out how to make this work now that we know more about time.

Frontend: There is already a spot for this just need to make sure we have the functionality in place.

**Comment by Cknutson100** [comment]
Need to add this calendar Picker to a modal with a clear button that sets dueDate back to null. ALSO need to style the calendar so that its prettier

**Comment by Cknutson100** [comment]
Initial styling is complete. Need to fix the new bug where the dates are off by 1 day. Something about the UTC again. @dylrob34

**Comment by dylrob34** [comment]
sounds like a utc vs local date thing, shouldn't be too bad.

**Comment by dylrob34** [comment]
Default date is 1970, needs to be either no date or the day it was made maybe?
